import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landing-page/Navbar";
import { SessionProvider } from "next-auth/react";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="chatbot"></div>
        {/* <Script
        strategy="beforeInteractive"
          src="https://cdn.jsdelivr.net/gh/diwanshuMidha/CDN@master/dist/assets/index-DK4vetTe.js
"
        ></Script>
        <Script strategy="beforeInteractive">Chatbot.mount(document.getElementById('chatbot'));</Script> */}
        <SessionProvider>
          <Navbar />
          <div className="pt-20">{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
